### PR TITLE
019 functional load page wbaccinelli

### PR DESCRIPTION
**Pull request by wbaccinelli**
Fixes https://github.com/EIT-ALIVE/eit_dash/issues/19

The Load page is now functional and it uses the new version of the eitprocessing. 
The continuous data are currently displayed, but not saved in the selection.

Note that while the newest branch of eitprocessing is still being updated, it's better to run the dashboard from a conda env rather than from poetry

### CODE REVIEW

**Comment by DaniBodor** [comment]
Hey @wbaccinelli , any reason this PR is still a draft or can do you want me to review it?

**Comment by DaniBodor** [comment]
I'm getting the following error:

Traceback (most recent call last):
  File "/home/dbodor/miniconda3/envs/dashalive/lib/python3.10/site-packages/eit_dash/callbacks/load_callbacks.py", line 134, in open_data_selector
    eit_data, continuous_data, sparse_data = EITData.from_path(
  File "/home/dbodor/miniconda3/envs/dashalive/lib/python3.10/site-packages/eitprocessing/eit_data/__init__.py", line 100, in from_path
    loaded_data = vendor_class._from_path(  # pylint: disable=protected-access
  File "/home/dbodor/miniconda3/envs/dashalive/lib/python3.10/site-packages/eitprocessing/eit_data/draeger.py", line 124, in _from_path
    ) = cls._convert_medibus_data(medibus_data, time)
  File "/home/dbodor/miniconda3/envs/dashalive/lib/python3.10/site-packages/eitprocessing/eit_data/draeger.py", line 139, in _convert_medibus_data
    continuous_data = ContinuousData(
TypeError: ContinuousData.__init__() missing 1 required positional argument: 'category'

**Comment by wbaccinelli** [comment]
At the moment we are not using the `eitprocessing` from the main branch, because we need the refactored version from [this branch](https://github.com/EIT-ALIVE/eitprocessing/tree/181_refactor_sequence_psomhorst). Therefore, to run the dashboard is now needed either to change the `pyptoject.toml` file and set the rev to the refactoring branch, or to create a conda env and install the `eitprocessing` package from the refactoring branch.

**Review by DaniBodor — APPROVED** [review]
nice, works well!

**Pull request merged**
