### PR TITLE
Adapt to new version

### PR DESCRIPTION
**Pull request by wbaccinelli**
Adapted the current code to the restructured code in `eitprocessing`

### CODE REVIEW

**Review by DaniBodor — CHANGES_REQUESTED** [review]
This is currently still pointing at the 181 branch of eitprocessing and the lock file was still pointing to a 3 week old version of that branch.

After updating that to the latest main, I am getting the following error when I hit confirm after pre-selecting the region I want:

> Callback error updating dataset-container.children
> 
> Traceback (most recent call last):
>   File "/home/dbodor/git/EIT-ALIVE/eit_dash/eit_dash/callbacks/load_callbacks.py", line 189, in show_info
>     selected = [signals_options[s]["label"] for s in selected_signals]
> TypeError: 'NoneType' object is not iterable

**Comment by DaniBodor** [comment]
Also, do you think that at this point it would be good to get the tests to work again? Or does this still depend on the tests in eitprocessing all working, because we are not quite there yet in that one :)

**Comment by wbaccinelli** [comment]
> Also, do you think that at this point it would be good to get the tests to work again? Or does this still depend on the tests in eitprocessing all working, because we are not quite there yet in that one :)

At this point, it depends more on how stable the functionalities in the dashboard are (which I think is the case). So, we can start also with writing the tests. There is already an [issue opened](#24) for this.

**Review by DaniBodor — APPROVED** [review]
Great!
Really happy that we finally got the main of eitprocessing in a functional state and good job making the dashboard work with that version!

**Comment by DaniBodor** [comment]
These brackets were slightly off in [this and/or statement](https://github.com/EIT-ALIVE/eit_dash/pull/29/commits/afaf454d86d3a033e0872b0af424d9cacf040dea). I think it probably evaluated the whole thing correctly nonetheless, but I fixed it to be sure.

**Pull request merged**
